SASS-10306
hmrc/income-tax-state-benefits-frontend pull request #98
Opened 2024-10-31 16:17 UTC by garytate123

### Description

Please include a brief summary of the change you've made and the issue that it fixes.

Add a link to the relevant story in Jira
[SASS-CHANGE-ME](ADD URL HERE)

### Checklist PR Reviewer

##### Before Reviewing

- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing

- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing

- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request?
  i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser

##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you run the smoke tests? (where applicable)
- [ ]  Have you run the performance tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of main?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised

- [ ]  Have you checked the PR Builder passes?

2024-11-01 12:03 UTC, baha-aboukoura requested changes

2024-11-01 12:03 UTC, baha-aboukoura commented on it/test/connectors/SectionCompletedConnectorISpec.scala
> +  //  def appConfig(host: String): AppConfig = new AppConfig(app.injector.instanceOf[ServicesConfig]) {
commented out code

2024-11-01 12:20 UTC, stephenheath101 approved these changes

2024-11-01 13:51 UTC, baha-aboukoura approved these changes

2024-11-01 14:43 UTC, basotia commented on app/controllers/SectionCompletedStateController.scala
> +    Future.successful(Redirect(appConfig.incomeTaxSubmissionOverviewUrl(taxYear)))
should this not be `Future.successful(Redirect(appConfig.commonTaskListUrl(taxYear)))`

2024-11-01 16:16 UTC, matthewwardcap commented on app/controllers/SectionCompletedStateController.scala
> +    val model = JourneyAnswers(mtditid, taxYear, benefitType.toString, Json.obj({
Should be benefitType.typeName currently

However we might add new attributes to the BenefitType model so just hold off at the moment

2024-11-01 16:18 UTC, matthewwardcap commented on app/controllers/SectionCompletedStateController.scala
> +    val model = JourneyAnswers(mtditid, taxYear, benefitType.toString, Json.obj({
We might need to hear back off team-b first but will discuss monday

2024-11-04 14:16 UTC, stephenheath101 submitted a review, later dismissed

2024-11-04 14:44 UTC, basotia submitted a review, later dismissed

2024-11-04 15:29 UTC, matthewwardcap approved these changes

2024-11-04 15:30 UTC, merged